import { useEffect, useState } from "react";
import {
  AlertCircle,
  BarChart3,
  Eye,
  FileText,
  Inbox,
  Sparkles,
} from "lucide-react";
import { Link, useNavigate } from "react-router-dom";

import { reportsApi } from "../../lib/api/reports";
import { ApiError } from "../../lib/apiClient";

import "./Reports.css";

function formatDate(isoString) {
  return new Date(isoString).toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function Reports() {
  const navigate = useNavigate();

  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [generating, setGenerating] = useState(false);

  const loadReports = async () => {
    setLoading(true);
    setError("");

    try {
      setReports(await reportsApi.getAll());
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to load reports.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadReports();
  }, []);

  const handleGenerate = async () => {
    setError("");
    setGenerating(true);

    try {
      const report = await reportsApi.generate();
      navigate(`/reports/${report.id}`);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to generate report.");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="reports-page">
      <div className="reports-header">
        <div>
          <h1>Reports</h1>
          <p>
            Generate a snapshot of your stock's current state - item counts,
            health, and warehouse distribution - that you can view or download at any time.
          </p>
        </div>

        <button
          type="button"
          className="btn btn-primary"
          onClick={handleGenerate}
          disabled={generating}
        >
          {generating ? <span className="spinner" /> : <Sparkles />}
          {generating ? "Generating..." : "Generate Stock Report"}
        </button>
      </div>

      {error && (
        <div
          className="banner banner-error"
          role="alert"
        >
          <AlertCircle />
          <span>{error}</span>
        </div>
      )}

      <div className="reports-card card">
        <div className="reports-card-header">
          <BarChart3 />
          <div>
            <h2>Stock Reports</h2>
            <p>Every report you've generated, newest first.</p>
          </div>
        </div>

        {loading ? (
          <div className="state-block">
            <span className="spinner" />
            Loading reports...
          </div>
        ) : reports.length === 0 ? (
          <div className="state-block">
            <Inbox />
            No reports generated yet. Click "Generate Stock Report" to create your first one.
          </div>
        ) : (
          <div className="report-table-wrapper">
            <table className="report-table">
              <thead>
                <tr>
                  <th>Generated</th>
                  <th>Generated By</th>
                  <th>Total Items</th>
                  <th className="actions-column">Actions</th>
                </tr>
              </thead>

              <tbody>
                {reports.map((report) => (
                  <tr key={report.id}>
                    <td>
                      <div className="report-name">
                        <div className="report-icon">
                          <FileText />
                        </div>
                        <span>{formatDate(report.generatedAt)}</span>
                      </div>
                    </td>
                    <td>{report.generatedByName}</td>
                    <td>{report.totalItems}</td>
                    <td className="actions-column">
                      <Link
                        to={`/reports/${report.id}`}
                        className="btn btn-outline report-view-btn"
                      >
                        <Eye />
                        View
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

export default Reports;
